- name: Install PostgreSQL 
  apt: "name={{ item }} state=present"
  with_items:
    - postgresql-15
    - postgresql-contrib
    - net-tools

- name: Configure PostgreSQL for connect master
  community.postgresql.postgresql_set:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  become_user: postgres
  with_dict: {listen_addresses: "{{ ansible_master_host }}", port: "{{ PORT }}"}
  notify:
    - Restart PostgreSQL

- name: Flush handlers
  meta: flush_handlers

- name: Stop Postgresql
  systemd:
    state: stopped
    name: postgresql

- name: Get directory stats
  stat:
    path: /var/lib/postgresql/15/main
  register: directory_stat

- name: Delete directory
  file:
    path: /var/lib/postgresql/15/main
    state: absent

- name: Create new directory
  file:
    path: /var/lib/postgresql/15/main
    state: directory
    owner: "{{ dir_info.stat.pw_name }}"
    group: "{{ dir_info.stat.gr_name }}"
    mode: "{{ dir_info.stat.mode }}"
  become_user: postgres

- name: Start replication
  shell:
    cmd: pg_basebackup -R -h {{ ansible_master_host }} -U {{ user_replication }} -D /var/lib/postgresql/15/main -P -p {{ PORT }}
  become_user: postgres

- name: Start PostgreSQL
  systemd:
    state: started
    name: postgresql