- name: Install packages
  apt: "name={{ item }} state=present"
  with_items:
    - postgresql-15
    - postgresql-contrib
    - net-tools

- name: "Create .pgpass"
  copy:
    dest: /var/lib/postgresql/.pgpass
    content: |
      {{ ansible_master_host }}:{{ PORT }}:*:{{ user_replication }}:{{ password_replication}}
    owner: postgres
    group: postgres
    mode: 0600

- name: "Stop postgresql"
  systemd:
    state: stopped
    name: postgresql

- name: "Get directory stats"
  stat:
    path: /var/lib/postgresql/15/main
  register: directory_stat

- name: "Delete directory"
  file:
    path: /var/lib/postgresql/15/main
    state: absent

- name: "Create directory"
  file:
    path: /var/lib/postgresql/15/main
    state: directory
    owner: "{{ directory_stat.stat.pw_name }}"
    group: "{{ directory_stat.stat.gr_name }}"
    mode: "{{ directory_stat.stat.mode }}"
  become_user: postgres

- name: "Answer Slave"
  debug:
    msg: "pg_basebackup -R -h {{ ansible_master_host }} -U {{ user_replication }} -D /var/lib/postgresql/15/main -P -p {{ PORT }}"

- name: "Start Replication"
  shell:
    cmd: pg_basebackup -R -h {{ ansible_master_host }} -U {{ user_replication }} -D /var/lib/postgresql/15/main -P -p {{ PORT }}
  environment:
    PGPASSFILE: "/var/lib/postgresql/.pgpass"
  become_user: postgres
  register: command_output

- name: "Answer Slave"
  debug:
    msg: "Slave - {{ command_output }}"

- name: "Start postgresql"
  systemd:
    state: started
    name: postgresql