- name: Install PostgreSQL 
  apt: "name={{ item }} state=present"
  with_items:
    - postgresql-15
    - postgresql-contrib
    - net-tools

- name: Create .pgpass
  copy:
    dest: /var/lib/postgresql/.pgpass
    content: |
      {{ ansible_master_host }}:{{ PORT }}:*:{{ user_replication }}:{{ password_replication}}
    owner: postgres
    group: postgres
    mode: 0600

- name: Flush handlers
  meta: flush_handlers

- name: Stop Postgresql
  systemd:
    state: stopped
    name: postgresql

- name: Get directory stats
  stat:
    path: /var/lib/postgresql/15/main
  register: directory_stat

- name: Delete directory
  file:
    path: /var/lib/postgresql/15/main
    state: absent

- name: Create new directory
  file:
    path: /var/lib/postgresql/15/main
    state: directory
    owner: "{{ directory_stat.stat.pw_name }}"
    group: "{{ directory_stat.stat.gr_name }}"
    mode: "{{ directory_stat.stat.mode }}"
  become_user: postgres

- name: Start replication
  shell:
    cmd: pg_basebackup -R -h {{ ansible_master_host }} -U {{ user_replication }} -D /var/lib/postgresql/15/main -P -p {{ PORT }}
  become_user: postgres

- name: Start PostgreSQL
  systemd:
    state: started
    name: postgresql