
- name: Install packages
  apt: "name={{ item }} state=present"
  with_items:
    - python3-full
    - virtualenv
    - python3-psycopg2
    - git
    
- name: Install dependencies
  apt:
    name: 
      - python3
      - python3-pip
    state: present

- name: Clone repository from git
  git:
    repo: https://github.com/spacecodboy/PT-START-Telegram-Bot.git
    dest: /home/{{ ansible_user }}/bot/
    version: bot

- name: Configure environment
  pip:
    requirements: /home/{{ ansible_user }}/bot/requirments.txt
    virtualenv: /home/{{ ansible_user }}/venv

- name: Copy .env
  copy:
    src: ./.env
    dest: /home/{{ ansible_user }}/bot/

- name: Start tg-bot
  shell:
    chdir: /home/{{ ansible_user }}/bot
    cmd: "../venv/bin/python main.py"