- name: Install dependencies
  apt:
    name: 
      - python3
      - python3-pip
    state: present

- name: Clone repository
  git:
    repo: https://github.com/Garret47/PT_Telegram_Bot.git
    dest: /home/user/bot/
    version: bot

- name: Activate Environment
  pip:
    requirements: /home/user/bot/requirements.txt
    virtualenv: /home/user/venv

- name: Copy .env
  copy:
    src: ./.env
    dest: /home/user/bot/