- name: "Install packages"
  apt: "name={{ item }} state=present"
  with_items:
    - python3-full
    - virtualenv
    - python3-psycopg2
    - git
    
- name: Install dependencies
  apt:
    name: 
      - python3
      - python3-pip
    state: present

- name: Clone repository
  git:
    repo: https://github.com/spacecodboy/PT-START-Telegram-Bot.git
    dest: /home/user/bot/
    version: bot

- name: Activate Environment
  pip:
    requirements: /home/user/bot/requirements.txt
    virtualenv: /home/user/venv

- name: Copy .env
  copy:
    src: ./.env
    dest: /home/user/bot/

- name: Start Bot
  shell:
    chdir: /home/user/bot
    cmd: "../venv/bin/python main.py >/dev/null 2>&1 &"